---
abstract: 'KyotoTycoon client library'
author:
  - 'Tokuhiro Matsuno <tokuhirom AAJKLFJEF GMAIL COM>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  File::Which: 0
  Test::More: 0.96
  Test::Requires: 0
  Test::TCP: 0
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.00'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: KyotoTycoon
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  Class::Accessor::Fast: 0
  Exporter: 5.63
  MIME::Base64: 0
  MIME::QuotedPrint: 0
  URI::Escape: 0
  WWW::Curl::Easy: 0
  parent: 0
  perl: 5.8.0
resources:
  license: http://dev.perl.org/licenses/
version: 0.01
